name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_ENV
      shell: bash

    - name: Cache Buildozer global directory
      uses: actions/cache@v2
      with:
        path: ~/.buildozer
        key: buildozer-${{ env.date }}-${{ hashFiles('buildozer.spec') }}

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: android debug

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: bin/*.apk
